openapi: 3.0.0
info:
  title: Merchant and Token Requestor APIs Components
  version: 0.3.0
paths:
components:
  schemas:
    Amount:
      type: object
      required:
        - currency
        - value
      description: >-
        The amount information for the transaction (in minor units).
      properties:
        currency:
          type: string
          minLength: 3
          maxLength: 3
          description: >-
            The three-character ISO 4217 code. The only supported currency is 'NOK'.
          example: NOK
          pattern: 'NOK'
        value:
          type: integer
          format: int64
          description: >-
            The payable amount that can be charged for the transaction. The transaction amount needs to be presented in minor units. For example, 100 NOK is submitted as 10000
          example: 10000

    AmountBreakdown:
      type: object
      required:
        - purchase
      description: AmountBreakdown specifies the different amount components. The cashback amount can only be included if the purchase amount is not zero.
      properties:
        purchase:
          $ref: '#/components/schemas/Amount'
        cashback:
          $ref: '#/components/schemas/Amount'

    encryptedPaymentCardholderAuthenticationData:
      type: string
      example: "eyJlbmMiOiJBMjU2Q0JDLUhTNTEyIiwiYWxnIjoiUlNBLU9BRVAtMjU2In0.f5nkE6FuGYkoa4usRQ1MhUJY34pYi31xgSiApiR1uP4tSXV3DNnY3N5Zq9Bnt1OucN2nJxAqCcND4G8TpGw9kofFcLcs5kXHg7nmIgjI8ZXTYx7GuZ_w6YxVTzCmjT5dpSlOQFkuCfJn2VdKnF4PjaqiKW9fWluOKorUZdsjsDl5PjIjf3ndqCtGEma6TBpKxLX0FnCZzvsVATCBcxqwKLvkAYFdFFtLfxe5OvW0PFsy4OjasODW3Kk55e58v5xXB8bP9hzr5S7sXFlzX2TG583MLLXG3K1E3XG0R262vs2cGgSA1B6zmujvmkpR4lLofwgahpO-ZrhGZtXE0-wFJw.NDB8Ln7XCf1q1p6ddRvnSw.PTBsKUkN5stmSQwrQ-jQLA.ece3W1q3AiMdg5QQbAd1tq_nQWLRkyNnk2mL1TP8fpQ"
      description: >-
        The Payment and Cardholder Authentication Data is encrypted according to the Java Web Encryption specification defined in RFC-7516.
        See schema PaymentCardholderAuthenticationData for decrypted data format

    PaymentCardholderAuthenticationData:
      type: object
      required:
        - iss
        - iat
        - paymentToken
        - verifiedCardholderAuthenticationSignedData
      properties:
        iss:
          $ref: '#/components/schemas/iss'
        iat:
          $ref: '#/components/schemas/iat'
        paymentToken:
          $ref: '#/components/schemas/PaymentToken'
        verifiedCardholderAuthenticationSignedData:
          $ref: '#/components/schemas/verifiedCardholderAuthenticationSignedData'

    PermissionGrant:
      type: object
      properties:
        type:
          type: string
          description: Type of the permission statement.
          enum:
            - payment.v1
            - approveAccount.v1
        iat:
          type: integer
          minimum: 1600000000
          maximum: 1800000000
        iss:
          type: string
        nonce:
          type: string
          description: The nonce from the permission statement
        sub:
          type: string
          description: |
            The primary identifier of the subject that granted the permission.
            The syntax is "identifierType:identifierValue". For
            NNINs, the identifierType is "nnin".
          example: "nnin:010112345"
        permissionId:
          type: string
          description: Unique id of the permission request
        digest:
          type: string
          format: bytes
          description: |
            The digest of the permission statement (URL-safe Base64-encoded SHA-256 hash of the permission statement bytes)

    Nonce:
      type: string
      minLength: 16
      maxLength: 64
      example: -MEDBtU6SeGtFsdHHI-rlA

    BasePermission:
      type: object
      required:
        - nonce
      properties:
        nonce:
          $ref: "#/components/schemas/Nonce"

    ApproveAccountPermissionV1:
      allOf:
        - $ref: "#/components/schemas/BasePermission"
        - type: object
          required:
            - accountNumber
            - merchantName
          properties:
            accountNumber:
              description: Account number
              type: string
              pattern: "^[0-9]{11}$"
              example: "12341212345"
            merchantName:
              type: string
              description: The Merchant where the card will be approved
              maxLength: 70

    PaymentBasePermissionV1:
      description: |
        This must satisfy PSD2 RTS Article 4 Authentication code and
        Article 5 Dynamic Linking
      type: object
      required:
        - paymentId
        - amount
        - currency
        - creditorName
      properties:
        paymentId:
          type: string
          description: |
            Payment id used for lookup at ASPSP.
            Payment id is not displayed to the user.
          example: Gm1rYOxUyzBQ03BLgr_EpEXq5HTwm-K-uUMroUNlRpI=
        amount:
          description: |
            The amount given with fractional digits, where fractions must be compliant to the currency definition.
            Up to 14 significant figures. Negative amounts are signed by minus.
            The decimal separator is a dot.
            **Example:**
            Valid representations for EUR with up to two decimals are:
              * 1056
              * 5768.2
              * -1.50
              * 5877.78
          type: string
          example: "5877.78"
        currency:
          type: string
          description: |
            ISO 4217 Alpha 3 currency code.
          minLength: 3
          maxLength: 3
          pattern: "[A-Z]{3}"
          example: "NOK"
        creditorName:
          $ref: '#/components/schemas/merchantDisplayName'

    PaymentPermissionV1:
      description: |
        This must satisfy PSD2 RTS Article 4 Authentication code and
        Article 5 Dynamic Linking
      allOf:
        - $ref: "#/components/schemas/BasePermission"
        - type: object
          required:
            - id
            - payments
          properties:
            id:
              type: string
              description: |
                Payment or basket id used for lookup at ASPSP.
                The user does not approve the id itself or anything implicitly inferred from the id.
              example: 1234-basket-567
            payments:
              type: array
              items:
                $ref: "#/components/schemas/PaymentBasePermissionV1"

    PaymentToken:
      type: object
      required:
        - pan
        - psn
        - expiryDate
      properties:
        pan:
          $ref: '#/components/schemas/pan'
        psn:
          $ref: '#/components/schemas/psn'
        expiryDate:
          $ref: '#/components/schemas/expiryDate'

    paymentId:
      type: string
      format: uuid
      example: "7f60d761-f27d-43d3-8ee9-53881b3c868d"
      description: >-
        The identifier for a specific payment.
    merchantName:
      type: string
      maxLength: 100
      description: >-
        The merchant name as registered in the Central Coordinating Register for Legal Entities (Enhetsregisteret).
    merchantDisplayName:
      type: string
      maxLength: 100
      description: >-
        The merchant's name, as shown to the cardholder, on receipts and on bank statements.
        This must be the exact string that was entered with the merchant enrollment.
    merchantReference:
      type: string
      maxLength: 80
      description: >-
        A reference set by the merchant to uniquely identify a payment request.
        BankAxept uses this reference in all communication with the merchant about the payment status.
        It is recommended that a unique value per payment is used. However, it is not a requirement.
    tokenRequestorReference:
      type: string
      maxLength: 80
      description: >-
        A reference set by the token requestor to uniquely identify an enrolment request.
        BankAxept uses this reference in all communication with the token requestor about the enrolment status.
        It is recommended that a unique value per enrolment is used. However, it is not a requirement.
    batchNumber:
      type: integer
      format: int64
      example: 1032
      description: >-
        The batch number identifying a specific settlement batch for a merchant.
    merchantId:
      type: string
      maxLength: 36
      example: "10030005"
      description: >-
        The merchant's unique identifier.
    merchantAggregatorId:
      type: string
      maxLength: 36
      description: >-
        The merchant aggregator's unique identifier.
    correlationId:
      type: string
      maxLength: 36
      example: "74313af1-e2cc-403f-85f1-6050725b01b6"
    iss:
      description: >-
        Identifies the principal that issued the JWT.
      type: string
      maxLength: 100
    iat:
      description: >-
        Identifies the time at which the JWT was issued.
      type: integer
      format: int64
      minimum: 1600000000
      maximum: 1800000000
    messageId:
      description: >-
        A unique identifier that guarantees message idempotency.
      type: string
      example: "74313af1-e2cc-403f-85f1-6050725b01b6"
    pan:
      type: string
      pattern: '^[0-9]{19}$'
      example: '9578540012345678901'
      description: >-
        The PAN of the payment token.
    psn:
      type: string
      pattern: '^[0-9]{1,3}$'
      example: '0'
      description: >-
        The PAN Sequence Number of the payment token.
    expiryDate:
      type: string
      pattern: '^[0-9]{2}(0[1-9]|1[0-2])$'
      example: '2108'
      description: >-
        The expiration date of the payment token (YYMM).
    tokenRequestorId:
      type: string
      pattern: "^[0-9]{1,11}$"
      example: "19474920408"
      description: >-
        The globally unique id for the token requestor.
    tokenId:
      type: string
      format: uuid
      example: "8140d6ef-be34-4cd4-9f67-c2c41d8a5573"
      description: >-
        The globally unique id for the token.
    authenticationURL:
      type: string
      description: URL to redirect the user to for completing authentication.
    verifiedCardholderAuthenticationSignedData:
      type: string
      example: "eyJhbGciOiJSUzI1NiIsIng1dCNTMjU2IjoiZGlnZXN0KGNlcnQpIn0.eyJhdXRoZW50aWNhdGVkRGF0YSI6eyJhY2NvdW50TnVtYmVyIjoiOTk5Nzc1MTIzNDUiLCJ0b2tlblJlcXVlc3Rvck5hbWUiOiJ0b2tlblJlcXVlc3Rvck5hbWUifSwibmluIjoiMTMwODc1MTIzNDUiLCJhdXRoZW50aWNhdGlvblNkbyI6Ijg0MzEzYWYxLWUyY2MtNDAzZi04NWYxLTYwNTA3MjViMDFiNiIsImF1dGhlbnRpY2F0aW9uQ3JlZGVudGlhbHNTZXQiOiJCQU5LSUQiLCJhdXRoZW50aWNhdGlvbkRhdGVUaW1lIjoiMjAxNy0wNy0yMVQxNzozMjoyOFoiLCJ2ZXJpZmljYXRpb25EYXRlVGltZSI6IjIwMTctMDctMjFUMTc6MzI6NDJaIn0.UoRYvKtrZrojIaq4P_iHjfA5Hx9SkEL-v_U0WMv78urpMbqsH2EpBdMuervwNWJKhc5vSp7ugO9LFYgE1PzSDUOYrMa6HfCJeRjlcgRODPC_exrX5lflUr7c-B8MJwSidCkOaKekrYexskYFpk4sdRTizbFdERzr3ZkgvBs_oa22KTYMwpipFO8i-Yf5XEE4zHGvh8abOsIY1yQQGhMwgr9RjNh_bi1wqL_FTJRPggsPjBMxrneWgy2veUbhHUq_JYqvSQxvhhJ_1RdE4gHXz0xaptmmbdZ5mtI1DyCRJEn6Io4x-0VIssApvljPjsMylcG2moeIDqUbjUAfxGrZcA"
      description: >-
        The Verified Cardholder Authentication Data is a signed JWT in JWS Compact Serialisation format according to the
        Java Web Signature specification defined in RFC-7515. See schema PermissionGrant for payload format.
    nin:
      type: string
      pattern: '^[0-9]{11}$'
      example: "13087512345"
      description: >-
        Norwegian national identity number for the cardholder.
    accountNumber:
      type: string
      pattern: '^[0-9]{11}$'
      example: "99977512345"
      description: >-
        The payment card's bank account number.
    authenticationDateTime:
      type: string
      format: date-time
    authenticationReference:
      type: string
    authenticationBindingMessage:
      type: string
      maxLength: 80
      description: >-
        Binding message for the cardholder authentication.

  parameters:
    paymentId:
      name: paymentId
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/paymentId'
    merchantId:
      name: merchantId
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/merchantId'
    batchNumber:
      name: batchNumber
      in: path
      description: 'The unique identifier of the settlement batch'
      required: true
      schema:
        $ref: '#/components/schemas/batchNumber'
    correlationId:
      name: X-Correlation-Id
      in: header
      description: 'A unique identifier to correlate HTTP requests between client and server.'
      required: false
      schema:
        $ref: '#/components/schemas/correlationId'
    messageId:
      name: messageId
      in: path
      description: 'The identifier of a request message'
      required: true
      schema:
        $ref: '#/components/schemas/messageId'
    tokenId:
      name: tokenId
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/tokenId'
    tokenRequestorReference:
      name: tokenRequestorReference
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/tokenRequestorReference'

  responses:
    200Ok:
      description: Request already received successfully.
    201Ok:
      description: Request received successfully.
    409Error:
      description: The request conflicts with a previously received request using the same message identifier.
    422Error:
      description: The request is not allowed for the current state.
    400Error:
      description: Client Error
    503Error:
      description: A temporary issue caused the request to not be processed. Retry is possible.
    500Error:
      description: Server Error

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
