openapi: 3.0.0
info:
  version: 0.3.0
  title: BankAxept ePayment Merchant API - Merchant Server
  description: BankAxept ePayment Merchant API - Merchant Server side

paths:
  /payments:
    description: Response to a payment request
    parameters:
      - $ref: '../components.yaml#/components/parameters/correlationId'
    post:
      operationId: paymentResponse
      requestBody:
        required: true
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/PaymentResponse'
      responses:
        '200':
          $ref: '../components.yaml#/components/responses/200Ok'
        '201':
          $ref: '../components.yaml#/components/responses/201Ok'
        '400':
          $ref: '../components.yaml#/components/responses/400Error'
        '409':
          $ref: '../components.yaml#/components/responses/409Error'
        '422':
          $ref: '../components.yaml#/components/responses/422Error'
        '500':
          $ref: '../components.yaml#/components/responses/500Error'
        '503':
          $ref: '../components.yaml#/components/responses/503Error'

  /payments/captures:
    description: Response to a capture request
    parameters:
      - $ref: '../components.yaml#/components/parameters/correlationId'
    post:
      operationId: captureResponse
      requestBody:
        required: true
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/CaptureResponse'
      responses:
        '200':
          $ref: '../components.yaml#/components/responses/200Ok'
        '201':
          $ref: '../components.yaml#/components/responses/201Ok'
        '400':
          $ref: '../components.yaml#/components/responses/400Error'
        '409':
          $ref: '../components.yaml#/components/responses/409Error'
        '422':
          $ref: '../components.yaml#/components/responses/422Error'
        '500':
          $ref: '../components.yaml#/components/responses/500Error'
        '503':
          $ref: '../components.yaml#/components/responses/503Error'

  /payments/refunds:
    description: Response to a refund request
    parameters:
      - $ref: '../components.yaml#/components/parameters/correlationId'
    post:
      operationId: refundResponse
      requestBody:
        required: true
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/RefundResponse'
      responses:
        '200':
          $ref: '../components.yaml#/components/responses/200Ok'
        '201':
          $ref: '../components.yaml#/components/responses/201Ok'
        '400':
          $ref: '../components.yaml#/components/responses/400Error'
        '409':
          $ref: '../components.yaml#/components/responses/409Error'
        '422':
          $ref: '../components.yaml#/components/responses/422Error'
        '500':
          $ref: '../components.yaml#/components/responses/500Error'
        '503':
          $ref: '../components.yaml#/components/responses/503Error'
  /settlements:
    description: Response to a cut-off request
    parameters:
      - $ref: '../components.yaml#/components/parameters/correlationId'
    post:
      operationId: cutOffResponse
      requestBody:
        required: true
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/CutOffResponse'
      responses:
        '200':
          $ref: '../components.yaml#/components/responses/200Ok'
        '201':
          $ref: '../components.yaml#/components/responses/201Ok'
        '400':
          $ref: '../components.yaml#/components/responses/400Error'
        '409':
          $ref: '../components.yaml#/components/responses/409Error'
        '422':
          $ref: '../components.yaml#/components/responses/422Error'
        '500':
          $ref: '../components.yaml#/components/responses/500Error'
        '503':
          $ref: '../components.yaml#/components/responses/503Error'

components:
  schemas:
    PaymentResponse:
      type: object
      required:
        - messageId
        - paymentId
        - merchantReference
        - status
      properties:
        messageId:
          $ref: '../components.yaml#/components/schemas/messageId'
        paymentId:
          $ref: '../components.yaml#/components/schemas/paymentId'
        merchantReference:
          $ref: '../components.yaml#/components/schemas/merchantReference'
        status:
          $ref: '#/components/schemas/PaymentStatus'
        authenticationBindingMessage:
          type: string
          maxLength: 80
          description: >-
            Binding message for the cardholder authentication.
        authorisationCode:
          type: string
          maxLength: 6
          description: >-
            Authorisation code: When the payment is authorised successfully, this field holds the authorisation code for the payment. When the payment is not authorised, this field is empty.
        batchNumber:
          $ref: '../components.yaml#/components/schemas/batchNumber'

    PaymentStatus:
      type: string
      example: Accepted
      description: |
        Status code specifying the result of the operation:
        * Authenticating - Cardholder authentication in progress.
        * AuthorisationApproved - Payment was authorised.
        * Rejected - Payment request was rejected.
        * RolledBack - Payment request was rolled back.
        * Cancelled - Payment request was cancelled.
        * AuthenticationFailed - Authentication validation failed.
        * AuthorisationFailed - Payment authorisation failed.
        * AuthorisationDeclined - Payment authorisation was declined.
      enum:
        - Authenticating
        - AuthorisationApproved
        - Rejected
        - RolledBack
        - Cancelled
        - AuthenticationFailed
        - AuthorisationFailed
        - AuthorisationDeclined

    CaptureResponse:
      type: object
      required:
        - messageId
        - paymentId
        - merchantReference
        - status
      properties:
        messageId:
          $ref: '../components.yaml#/components/schemas/messageId'
        paymentId:
          $ref: '../components.yaml#/components/schemas/paymentId'
        merchantReference:
          $ref: '../components.yaml#/components/schemas/merchantReference'
        status:
          $ref: '#/components/schemas/CaptureStatus'
        timeCreated:
          type: string
          format: date-time
          description: >-
            The time and date the request was created. The date fields use the YYYY-MM-DDThh:mm:ss.sssZ date ISO 8601 format. Times are returned in the UTC time zone.
        batchNumber:
          $ref: '../components.yaml#/components/schemas/batchNumber'

    RefundResponse:
      type: object
      required:
        - messageId
        - paymentId
        - merchantReference
        - status
      properties:
        messageId:
          $ref: '../components.yaml#/components/schemas/messageId'
        paymentId:
          $ref: '../components.yaml#/components/schemas/paymentId'
        merchantReference:
          $ref: '../components.yaml#/components/schemas/merchantReference'
        status:
          $ref: '#/components/schemas/RefundStatus'
        timeCreated:
          type: string
          format: date-time
          description: >-
            The time and date the request was created. The date fields use the YYYY-MM-DDThh:mm:ss.sssZ date ISO 8601 format. Times are returned in the UTC time zone.
        batchNumber:
          $ref: '../components.yaml#/components/schemas/batchNumber'

    CutOffResponse:
      type: object
      properties:
        batchNumber:
          $ref: '../components.yaml#/components/schemas/batchNumber'
        messageId:
          $ref: '../components.yaml#/components/schemas/messageId'
        merchantId:
          $ref: '../components.yaml#/components/schemas/merchantId'
        creditAmount:
          type: integer
          format: int64
        creditCount:
          type: integer
          format: int64
        debitAmount:
          type: integer
          format: int64
        debitCount:
          type: integer
          format: int64
        creditReversalAmount:
          type: integer
          format: int64
        creditReversalCount:
          type: integer
          format: int64
        debitReversalAmount:
          type: integer
          format: int64
        debitReversalCount:
          type: integer
          format: int64

    CaptureStatus:
      type: string
      example: Approved
      description: |
        Code specifying the result of the operation:
        * Approved - Capture request was approved.
        * Declined - Capture request was declined.
      enum:
        - Approved
        - Declined

    RefundStatus:
      type: string
      example: Approved
      description: |
        Code specifying the result of the operation:
        * Approved - Refund request was approved.
        * Declined - Refund request was declined.
        * Failed - Refund request failed.
      enum:
        - Approved
        - Declined
        - Failed
