openapi: 3.0.0
info:
  version: 0.3.0
  title: BankAxept ePayment Merchant API - Merchant Server
  description: BankAxept ePayment Merchant API - Merchant Server side

paths:
  /v1/payments:
    description: Response to a payment request
    parameters:
      - $ref: '../components.yaml#/components/parameters/correlationId'
    post:
      operationId: paymentResponse
      requestBody:
        required: true
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/PaymentResponse'
      responses:
        '200':
          $ref: '../components.yaml#/components/responses/200Ok'
        '201':
          $ref: '../components.yaml#/components/responses/201Ok'
        '400':
          $ref: '../components.yaml#/components/responses/400Error'
        '409':
          $ref: '../components.yaml#/components/responses/409Error'
        '422':
          $ref: '../components.yaml#/components/responses/422Error'
        '500':
          $ref: '../components.yaml#/components/responses/500Error'
        '503':
          $ref: '../components.yaml#/components/responses/503Error'

  /v1/payments/captures:
    description: Response to a capture request
    parameters:
      - $ref: '../components.yaml#/components/parameters/correlationId'
    post:
      operationId: captureResponse
      requestBody:
        required: true
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/CaptureResponse'
      responses:
        '200':
          $ref: '../components.yaml#/components/responses/200Ok'
        '201':
          $ref: '../components.yaml#/components/responses/201Ok'
        '400':
          $ref: '../components.yaml#/components/responses/400Error'
        '409':
          $ref: '../components.yaml#/components/responses/409Error'
        '422':
          $ref: '../components.yaml#/components/responses/422Error'
        '500':
          $ref: '../components.yaml#/components/responses/500Error'
        '503':
          $ref: '../components.yaml#/components/responses/503Error'

  /v1/payments/refunds:
    description: Response to a refund request
    parameters:
      - $ref: '../components.yaml#/components/parameters/correlationId'
    post:
      operationId: refundResponse
      requestBody:
        required: true
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/RefundResponse'
      responses:
        '200':
          $ref: '../components.yaml#/components/responses/200Ok'
        '201':
          $ref: '../components.yaml#/components/responses/201Ok'
        '400':
          $ref: '../components.yaml#/components/responses/400Error'
        '409':
          $ref: '../components.yaml#/components/responses/409Error'
        '422':
          $ref: '../components.yaml#/components/responses/422Error'
        '500':
          $ref: '../components.yaml#/components/responses/500Error'
        '503':
          $ref: '../components.yaml#/components/responses/503Error'
  /v1/settlements:
    description: Response to a cut-off request
    parameters:
      - $ref: '../components.yaml#/components/parameters/correlationId'
    post:
      operationId: cutOffResponse
      requestBody:
        required: true
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/CutOffResponse'
      responses:
        '200':
          $ref: '../components.yaml#/components/responses/200Ok'
        '201':
          $ref: '../components.yaml#/components/responses/201Ok'
        '400':
          $ref: '../components.yaml#/components/responses/400Error'
        '409':
          $ref: '../components.yaml#/components/responses/409Error'
        '422':
          $ref: '../components.yaml#/components/responses/422Error'
        '500':
          $ref: '../components.yaml#/components/responses/500Error'
        '503':
          $ref: '../components.yaml#/components/responses/503Error'

components:
  schemas:
    PaymentResponse:
      type: object
      required:
        - messageId
        - paymentId
        - merchantReference
        - status
      properties:
        messageId:
          $ref: '../components.yaml#/components/schemas/messageId'
        paymentId:
          $ref: '../components.yaml#/components/schemas/paymentId'
        merchantReference:
          $ref: '../components.yaml#/components/schemas/merchantReference'
        status:
          $ref: '#/components/schemas/PaymentStatus'
        stan:
          $ref: '#/components/schemas/stan'
        responseCode:
          $ref: '#/components/schemas/responseCode'
        authorisationCode:
          $ref: '#/components/schemas/authorisationCode'
        batchNumber:
          $ref: '../components.yaml#/components/schemas/batchNumber'

    PaymentStatus:
      type: string
      example: Accepted
      description: |
        Status code specifying the result of the operation:
        * AuthorisationApproved - Payment was authorised.
        * Rejected - Payment request was rejected.
        * RolledBack - Payment request was rolled back.
        * Cancelled - Payment request was cancelled.
        * AuthenticationFailed - Authentication validation failed.
        * AuthorisationFailed - Payment authorisation failed.
        * AuthorisationDeclined - Payment authorisation was declined.
      enum:
        - AuthorisationApproved
        - Rejected
        - RolledBack
        - Cancelled
        - AuthenticationFailed
        - AuthorisationFailed
        - AuthorisationDeclined

    CaptureResponse:
      type: object
      required:
        - messageId
        - paymentId
        - merchantReference
        - status
      properties:
        messageId:
          $ref: '../components.yaml#/components/schemas/messageId'
        paymentId:
          $ref: '../components.yaml#/components/schemas/paymentId'
        merchantReference:
          $ref: '../components.yaml#/components/schemas/merchantReference'
        status:
          $ref: '#/components/schemas/CaptureStatus'
        errorCode:
          $ref: '#/components/schemas/ErrorCode'
        timeCreated:
          type: string
          format: date-time
          description: >-
            The time and date the request was created. The date fields use the YYYY-MM-DDThh:mm:ss.sssZ date ISO 8601 format. Times are returned in the UTC time zone.
        batchNumber:
          $ref: '../components.yaml#/components/schemas/batchNumber'

    RefundResponse:
      type: object
      required:
        - messageId
        - paymentId
        - merchantReference
        - status
      properties:
        messageId:
          $ref: '../components.yaml#/components/schemas/messageId'
        paymentId:
          $ref: '../components.yaml#/components/schemas/paymentId'
        merchantReference:
          $ref: '../components.yaml#/components/schemas/merchantReference'
        status:
          $ref: '#/components/schemas/RefundStatus'
        errorCode:
          $ref: '#/components/schemas/ErrorCode'
        timeCreated:
          type: string
          format: date-time
          description: >-
            The time and date the request was created. The date fields use the YYYY-MM-DDThh:mm:ss.sssZ date ISO 8601 format. Times are returned in the UTC time zone.
        stan:
          $ref: '#/components/schemas/stan'
        responseCode:
          $ref: '#/components/schemas/responseCode'
        authorisationCode:
          $ref: '#/components/schemas/authorisationCode'
        batchNumber:
          $ref: '../components.yaml#/components/schemas/batchNumber'

    CutOffResponse:
      type: object
      required:
        - batchNumber
        - merchantId
        - messageId
        - status
      properties:
        batchNumber:
          $ref: '../components.yaml#/components/schemas/batchNumber'
        currentBatchNumber:
          type: integer
          format: int64
          example: 1032
          description: >-
            Indicates the current settlement batch for a merchant.
            This information is provided only if the status is Declined.
        messageId:
          $ref: '../components.yaml#/components/schemas/messageId'
        merchantId:
          $ref: '../components.yaml#/components/schemas/merchantId'
        status:
          $ref: '#/components/schemas/CutOffStatus'
        creditAmount:
          type: integer
          format: int64
        creditCount:
          type: integer
          format: int64
        debitAmount:
          type: integer
          format: int64
        debitCount:
          type: integer
          format: int64
        creditReversalAmount:
          type: integer
          format: int64
        creditReversalCount:
          type: integer
          format: int64
        debitReversalAmount:
          type: integer
          format: int64
        debitReversalCount:
          type: integer
          format: int64

    CaptureStatus:
      type: string
      example: Approved
      description: |
        Code specifying the result of the operation:
        * Approved - Capture request was approved.
        * Declined - Capture request was declined.
      enum:
        - Approved
        - Declined

    RefundStatus:
      type: string
      example: Approved
      description: |
        Code specifying the result of the operation:
        * Approved - Refund request was approved.
        * Declined - Refund request was declined.
        * Failed - Refund request failed.
      enum:
        - Approved
        - Declined
        - Failed

    CutOffStatus:
      type: string
      example: Approved
      description: |
        Code specifying the result of the operation:
        * Approved - CutOff request was approved.
        * Declined - CutOff request was declined.
      enum:
        - Approved
        - Declined

    stan:
      type: string
      maxLength: 6
      description: >-
        System trace audit number; a number assigned by the payment initiator to identify the transaction.

    responseCode:
      type: string
      maxLength: 2
      description: >-
        Response code from issuer or processor when request was approved or declined.

    authorisationCode:
      type: string
      maxLength: 6
      description: >-
        A code from the issuer identifying a successful authorisation.

    ErrorCode:
      type: string
      example: Declined
      description: |
        Only provided in Failure/Declined scenarios. 
        Code specifying the cause of failure for the Refund or Capture operation:
        * Unavailable - Retryable.
        * InitiationFailed - Retryable.
        * Failed - Not Retryable. Review configuration of integration.
        * Incomprehensible - Retryable, possible network issue or ongoing incident.
        * Blocked - Transaction is blocked, recommend contacting issuer.
        * TransactionNotPermitted - Not permitted, review configuration integration. For example length of time since original transaction or activation of functionality on BAX account.
        * Declined - Not retryable. Declined by business rules.
      enum:
        - Unavailable
        - InitiationFailed
        - Failed
        - Incomprehensible
        - TransactionNotPermitted
        - Blocked
        - Declined
