openapi: 3.0.0
info:
  version: 0.4.0
  title: BankAxept ePayment Token Requestor API - Token Requestor
  description: BankAxept ePayment Token Requestor APIs - Token Requestor side

paths:
  /payment-tokens:
    description: EnrolCard callback
    post:
      operationId: addToken
      parameters:
        - $ref: '../components.yaml#/components/parameters/correlationId'
      requestBody:
        required: true
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/EnrolCardCallbackData'
      responses:
        '200':
          $ref: '../components.yaml#/components/responses/200Ok'
        '201':
          $ref: '../components.yaml#/components/responses/201Ok'
        '400':
          $ref: '../components.yaml#/components/responses/400Error'
        '409':
          $ref: '../components.yaml#/components/responses/409Error'
        '422':
          $ref: '../components.yaml#/components/responses/422Error'
        '500':
          $ref: '../components.yaml#/components/responses/500Error'
        '503':
          $ref: '../components.yaml#/components/responses/503Error'
  /payment-tokens/{tokenId}/suspensions:
    description: Payment token suspension notification
    post:
      operationId: suspendToken
      parameters:
        - $ref: '../components.yaml#/components/parameters/tokenId'
      requestBody:
        required: true
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/TokenUpdateData'
      responses:
        '200':
          $ref: '../components.yaml#/components/responses/200Ok'
        '201':
          $ref: '../components.yaml#/components/responses/201Ok'
        '400':
          $ref: '../components.yaml#/components/responses/400Error'
        '409':
          $ref: '../components.yaml#/components/responses/409Error'
        '422':
          $ref: '../components.yaml#/components/responses/422Error'
        '500':
          $ref: '../components.yaml#/components/responses/500Error'
        '503':
          $ref: '../components.yaml#/components/responses/503Error'
  /payment-tokens/{tokenId}/resumptions:
    description: Payment token resumption notification
    post:
      operationId: resumeToken
      parameters:
        - $ref: '../components.yaml#/components/parameters/tokenId'
      requestBody:
        required: true
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/TokenUpdateData'
      responses:
        '200':
          $ref: '../components.yaml#/components/responses/200Ok'
        '201':
          $ref: '../components.yaml#/components/responses/201Ok'
        '400':
          $ref: '../components.yaml#/components/responses/400Error'
        '409':
          $ref: '../components.yaml#/components/responses/409Error'
        '422':
          $ref: '../components.yaml#/components/responses/422Error'
        '500':
          $ref: '../components.yaml#/components/responses/500Error'
        '503':
          $ref: '../components.yaml#/components/responses/503Error'
  /payment-tokens/{tokenId}:
    description: Payment token deletion notification
    delete:
      operationId: deleteToken
      parameters:
        - $ref: '../components.yaml#/components/parameters/tokenId'
      responses:
        '200':
          $ref: '../components.yaml#/components/responses/200Ok'
        '201':
          $ref: '../components.yaml#/components/responses/201Ok'
        '400':
          $ref: '../components.yaml#/components/responses/400Error'
        '409':
          $ref: '../components.yaml#/components/responses/409Error'
        '422':
          $ref: '../components.yaml#/components/responses/422Error'
        '500':
          $ref: '../components.yaml#/components/responses/500Error'
        '503':
          $ref: '../components.yaml#/components/responses/503Error'
  /payment-tokens/{tokenId}/expirations:
    description: Payment token expiry date extension notification
    post:
      operationId: extendExpiration
      parameters:
        - $ref: '../components.yaml#/components/parameters/tokenId'
      requestBody:
        required: true
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/TokenExpiryExtensionData'
      responses:
        '200':
          $ref: '../components.yaml#/components/responses/200Ok'
        '201':
          $ref: '../components.yaml#/components/responses/201Ok'
        '400':
          $ref: '../components.yaml#/components/responses/400Error'
        '409':
          $ref: '../components.yaml#/components/responses/409Error'
        '422':
          $ref: '../components.yaml#/components/responses/422Error'
        '500':
          $ref: '../components.yaml#/components/responses/500Error'
        '503':
          $ref: '../components.yaml#/components/responses/503Error'

components:
  schemas:
    EnrolCardCallbackData:
      type: object
      required:
        - code
        - tokenId
        - messageId
      properties:
        code:
          $ref: '#/components/schemas/EnrolCardCode'
        tokenId:
          $ref: '../components.yaml#/components/schemas/tokenId'
        messageId:
          $ref: '../components.yaml#/components/schemas/messageId'
        result:
          $ref: '#/components/schemas/EnrolCardCallbackResult'
        errorMessage:
          type: string

    EnrolCardCallbackResult:
      type: object
      required:
        - tokenRequestorId
        - paymentToken
        - accountNumberLastFourDigits
        - issuerId
      properties:
        tokenRequestorId:
          $ref: '../components.yaml#/components/schemas/tokenRequestorId'
        paymentToken:
          $ref: '../components.yaml#/components/schemas/TokenPaymentData'
        accountNumberLastFourDigits:
          type: string
          pattern: '^[0-9]{4}$'
        issuerId:
          description: |
            An identifier for the issuer of the payment card. "Company Bankreg number" (konsern bankreg.nummer) of issuer.
          type: string
          pattern: '^[0-9]{4}$'
          example: "7001"

    EnrolCardCode:
      type: string
      example: Accepted
      description: |
        Code specifying the result of the operation:
        * Accepted - Enrolment was accepted.
        * Rejected - Enrolment was rejected.
        * Failed - Enrolment failed.
      enum:
        - Accepted
        - Rejected
        - Failed

    TokenUpdateData:
      type: object
      required:
        - messageId
        - status
      properties:
        messageId:
          $ref: '../components.yaml#/components/schemas/messageId'
        status:
          $ref: '#/components/schemas/TokenUpdateStatus'

    TokenUpdateStatus:
      type: string
      example: Active
      description: |
        Updated status of the token:
        * Active - Token is active
        * Suspended - Token is suspended
        * Deleted - Token is deleted
      enum:
        - Active
        - Suspended
        - Deleted

    TokenExpiryExtensionData:
      type: object
      required:
        - messageId
        - tokenExpiryDate
      properties:
        messageId:
          $ref: '../components.yaml#/components/schemas/messageId'
        tokenExpiryDate:
          $ref: '../components.yaml#/components/schemas/tokenExpiryDate'
