openapi: 3.0.0
info:
  version: 0.4.0
  title: BankAxept ePayment Token Requestor API - Token Requestor
  description: BankAxept ePayment Token Requestor APIs - Token Requestor side

paths:
  /v1/payment-tokens:
    description: EnrolCard callback
    post:
      operationId: addToken
      parameters:
        - $ref: '../components.yaml#/components/parameters/correlationId'
      requestBody:
        required: true
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/CardEnrolmentResponse'
      responses:
        '200':
          $ref: '../components.yaml#/components/responses/200Ok'
        '201':
          $ref: '../components.yaml#/components/responses/201Ok'
        '400':
          $ref: '../components.yaml#/components/responses/400Error'
        '409':
          $ref: '../components.yaml#/components/responses/409Error'
        '422':
          $ref: '../components.yaml#/components/responses/422Error'
        '500':
          $ref: '../components.yaml#/components/responses/500Error'
        '503':
          $ref: '../components.yaml#/components/responses/503Error'
  /v1/payment-tokens/suspensions:
    description: Payment token suspension notification
    post:
      operationId: suspendToken
      parameters:
        - $ref: '../components.yaml#/components/parameters/correlationId'
      requestBody:
        required: true
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/TokenUpdateData'
      responses:
        '200':
          $ref: '../components.yaml#/components/responses/200Ok'
        '201':
          $ref: '../components.yaml#/components/responses/201Ok'
        '400':
          $ref: '../components.yaml#/components/responses/400Error'
        '409':
          $ref: '../components.yaml#/components/responses/409Error'
        '422':
          $ref: '../components.yaml#/components/responses/422Error'
        '500':
          $ref: '../components.yaml#/components/responses/500Error'
        '503':
          $ref: '../components.yaml#/components/responses/503Error'
  /v1/payment-tokens/resumptions:
    description: Payment token resumption notification
    post:
      operationId: resumeToken
      parameters:
        - $ref: '../components.yaml#/components/parameters/correlationId'
      requestBody:
        required: true
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/TokenUpdateData'
      responses:
        '200':
          $ref: '../components.yaml#/components/responses/200Ok'
        '201':
          $ref: '../components.yaml#/components/responses/201Ok'
        '400':
          $ref: '../components.yaml#/components/responses/400Error'
        '409':
          $ref: '../components.yaml#/components/responses/409Error'
        '422':
          $ref: '../components.yaml#/components/responses/422Error'
        '500':
          $ref: '../components.yaml#/components/responses/500Error'
        '503':
          $ref: '../components.yaml#/components/responses/503Error'
  /v1/payment-tokens/{tokenRequestorReference}:
    description: Payment token deletion notification
    delete:
      operationId: deleteToken
      parameters:
        - $ref: '../components.yaml#/components/parameters/tokenRequestorReference'
        - $ref: '../components.yaml#/components/parameters/correlationId'
      responses:
        '200':
          $ref: '../components.yaml#/components/responses/200Ok'
        '201':
          $ref: '../components.yaml#/components/responses/201Ok'
        '400':
          $ref: '../components.yaml#/components/responses/400Error'
        '409':
          $ref: '../components.yaml#/components/responses/409Error'
        '422':
          $ref: '../components.yaml#/components/responses/422Error'
        '500':
          $ref: '../components.yaml#/components/responses/500Error'
        '503':
          $ref: '../components.yaml#/components/responses/503Error'
  /v1/payment-tokens/expirations:
    description: Payment token expiry date extension notification
    post:
      operationId: extendExpiration
      requestBody:
        required: true
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/TokenExpiryExtensionData'
      responses:
        '200':
          $ref: '../components.yaml#/components/responses/200Ok'
        '201':
          $ref: '../components.yaml#/components/responses/201Ok'
        '400':
          $ref: '../components.yaml#/components/responses/400Error'
        '409':
          $ref: '../components.yaml#/components/responses/409Error'
        '422':
          $ref: '../components.yaml#/components/responses/422Error'
        '500':
          $ref: '../components.yaml#/components/responses/500Error'
        '503':
          $ref: '../components.yaml#/components/responses/503Error'

components:
  schemas:
    CardEnrolmentResponse:
      type: object
      required:
        - messageId
        - tokenId
        - tokenRequestorReference
        - status
      properties:
        messageId:
          $ref: '../components.yaml#/components/schemas/messageId'
        tokenId:
          $ref: '../components.yaml#/components/schemas/tokenId'
        tokenRequestorReference:
          $ref: '../components.yaml#/components/schemas/tokenRequestorReference'
        status:
          $ref: '#/components/schemas/EnrolmentStatus'
        errorCode:
          $ref: '#/components/schemas/ErrorCode'
        paymentToken:
          $ref: '../components.yaml#/components/schemas/PaymentToken'
        accountNumberLastFourDigits:
          type: string
          pattern: '^[0-9]{4}$'
        issuerId:
          description: |
            An identifier for the issuer of the payment card. "Company Bankreg number" (konsern bankreg.nummer) of issuer.
          type: string
          pattern: '^[0-9]{4}$'
          example: "7001"

    EnrolmentStatus:
      type: string
      example: Accepted
      description: |
        Code specifying the result of the operation:
        * Accepted - Enrolment was accepted.
        * Rejected - Enrolment was rejected.
        * Failed - Enrolment failed.
      enum:
        - Accepted
        - Rejected
        - Failed

    ErrorCode:
      type: string
      example: CardNotActivated
      description: |
        Code specifying the result of the operation:
        * EnrolmentOperationFailed - Retryable.
        * Timeout - Retryable.
        * IllegalOperation - Not Retryable. Review configuration of integration.
        * UnknownCard - Card is not known. Recommend contacting card issuer.
        * CardNotActivated - Card is not activated for use. Recommend activating card. Often by performing an offline transaction first in the case of a new card.
        * CardExpired - Card is expired. Recommend updating to a new card.
        * CardSuspended - Card is suspended. Recommend contacting card issuer.
        * CardRevoked - Card is revoked. Recommend contacting card issuer.
        * NoEligibleCardsFound - No eligible cards found. Recommend contacting card issuer.
        * FpanProvCountExceeded - Card enroled too many times.
        * InvalidFundingPan - Invalid funding PAN. Recommend contacting card issuer.
      enum:
        - EnrolmentOperationFailed
        - IllegalOperation
        - Timeout
        - UnknownCard
        - CardNotActivated
        - CardExpired
        - CardSuspended
        - CardRevoked
        - NoEligibleCardsFound
        - FpanProvCountExceeded
        - InvalidFundingPan

    TokenUpdateData:
      type: object
      required:
        - messageId
        - tokenId
        - tokenRequestorReference
      properties:
        messageId:
          $ref: '../components.yaml#/components/schemas/messageId'
        tokenId:
          $ref: '../components.yaml#/components/schemas/tokenId'
        tokenRequestorReference:
          $ref: '../components.yaml#/components/schemas/tokenRequestorReference'

    TokenExpiryExtensionData:
      type: object
      required:
        - messageId
        - tokenId
        - tokenRequestorReference
        - tokenExpiryDate
      properties:
        messageId:
          $ref: '../components.yaml#/components/schemas/messageId'
        tokenId:
          $ref: '../components.yaml#/components/schemas/tokenId'
        tokenRequestorReference:
          $ref: '../components.yaml#/components/schemas/tokenRequestorReference'
        tokenExpiryDate:
          $ref: '../components.yaml#/components/schemas/expiryDate'
