openapi: 3.0.1
info:
  version: 0.0.1
  title: BankAxept ePayment Cert-Butler API - ePayment Platform
  description: BankAxept ePayment Certificates Butler API
servers:
  - url: https://api.epp-stoetest.cloud/certificates
paths:
  /wallet:
    get:
      operationId: certificates
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CertificateData"
  /merchant:
    get:
      operationId: certificates
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CertificateData"
components:
  schemas:
    CertificateData:
      type: object
      properties:
        name:
          type: string
        subject:
          type: string
        notBefore:
          type: string
          format: date-time
        expiresOn:
          type: string
          format: date-time
        certificate:
          type: string
